### ISSUE TITLE
Code and changelog for v3?

### ISSUE THREAD

**Issue by bengry** [ChuckJonas/ts-force#95]
On npm [ts-force](https://www.npmjs.com/package/ts-force) and [`ts-force-gen`](https://www.npmjs.com/package/ts-force-gen) are on `v3.0.0-rc.8` (published 10 days ago), but the latest version in this repo is `2.7.0` on `master` and `3.0.0-rc.3` on the `3.0` branch.

Where can I find the updated code for `3.0.0-rc.4` through `3.0.0-rc.8`? Also, where can I find a changelog, if one exists, for those versions.

**Comment by ChuckJonas** [comment]
the rc versions should not have technically been marked as latest on npm.  Even though [3.x](https://github.com/ChuckJonas/ts-force/pull/79) is probably better and more stable, I haven't had a chance to finish documenting and testing.  

I just pushed my recent local commits, including a change log of everything since 2.7.   

3.x got sidetracked by 'grand visions' of fixing all the less than ideal design decisions... However, I've recently been working through some of the remaining items and do actually plan on releasing it soon.  Strict support (including your PR) is part of that.
